require("setup.setup-auto-pairs")
require("setup.setup-cmp")
require("setup.setup-colorscheme")
require("setup.setup-lsp")
require("setup.setup-simpylfold")
require("setup.setup-telescope")
require("setup.setup-treesitter")
